### ISSUE TITLE
when debug, show qt app has some problems

### ISSUE THREAD

**Issue by jogxag** [kambala-decapitator/qt-inside-ios-native#1]
OS version: macOS Sonoma 14.2
Xcode version:  15.0.1
Qt version: 5.15.2

I have used CMake to compile the project with README.  Then I run the project in iPhone Device(iOS 17.0), all of these are ok.
But when I click the "Show Qt app", there will show a mask without qt's widget. At this time, let the app minimize, then click the ios-app's icon to make it activity, it will show qt's widget, but there is not reaction, when I clicked the QPushButton or the QComboBox!!! How could I fix these problem?Thanks.
![Uploading 截屏 2023-12-13 16.18.35.jpeg…]()
![Uploading IMG_0004 2.PNG…]()
![Uploading IMG_0005.PNG…]()

**Comment by jogxag** [comment]
![截屏 2023-12-13 16 18 35](https://github.com/kambala-decapitator/qt-inside-ios-native/assets/9649737/2432bcc6-ca56-45d9-8253-f11e00462f94)
![IMG_0004 2](https://github.com/kambala-decapitator/qt-inside-ios-native/assets/9649737/6ddfc837-0ef4-478c-b553-a9128e704abc)
![IMG_0005](https://github.com/kambala-decapitator/qt-inside-ios-native/assets/9649737/913b6b41-ce9f-4656-b371-1e324bb7daa4)

**Comment by kambala-decapitator** [comment]
just tested on the following configurations and can't reproduce. I suspect that you use 5.15.2 prebuilt version from the Qt installer - it's very old (the version itself as well as the toolchain that was used to build it), can only suggest to build Qt manually with a more recent toolchain (Xcode version).

Environment: macOS Sonoma, Qt 5.15.8 built with Xcode 14.2, iPhone XR running iOS 17.2. Tested the app with toolchains:
- Xcode 14.2
- Xcode 15.0.1
